name: Ollie Reardon
description: "Web Developer by Day, Game Developer by Night"
url: ojdon.github.io
markdown: redcarpet
highlighter: pygments
permalink: /blog/:title
paginate: 5
paginate_path: "blog/page:num"
