name: Ollie Reardon
description: "Web Developer by Day, Game Developer by Night"
highlighter: rouge
permalink: /blog/:title
paginate: 5
paginate_path: "blog/page:num"
plugins:
  - jekyll-sitemap
  - jekyll-paginate
sass:
  style: compressed # possible values: nested expanded compact compressed
  load_paths:
    - _sass
    - node_modules