name: Ollie Reardon
description: "Web Developer by Day, Game Developer by Night"
markdown: redcarpet
highlighter: pygments
permalink: /blog/:title
paginate: 5
paginate_path: "blog/page:num"
gems:
  - jekyll-sitemap
  - jekyll-paginate